spring:
  profiles:
    active: db
  messages:
    encoding: UTF-8

# 此处设置无用
#logging:
#  level:
#    root:  ERROR
#    org.springframework:  ERROR
#    org.mybatis:  ERROR
#    org.linlinjava.litemall.db:  DEBUG