package org.xhh.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Activity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.place
     *
     * @mbg.generated
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.images_index
     *
     * @mbg.generated
     */
    private String imagesIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.isplay
     *
     * @mbg.generated
     */
    private String isplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.territory
     *
     * @mbg.generated
     */
    private String territory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.territory2
     *
     * @mbg.generated
     */
    private String territory2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.createid
     *
     * @mbg.generated
     */
    private String createid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.createtime
     *
     * @mbg.generated
     */
    private LocalDateTime createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.updateid
     *
     * @mbg.generated
     */
    private String updateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.updatetime
     *
     * @mbg.generated
     */
    private LocalDateTime updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.name
     *
     * @return the value of activity.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.name
     *
     * @param name the value for activity.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.place
     *
     * @return the value of activity.place
     *
     * @mbg.generated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.place
     *
     * @param place the value for activity.place
     *
     * @mbg.generated
     */
    public void setPlace(String place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.images_index
     *
     * @return the value of activity.images_index
     *
     * @mbg.generated
     */
    public String getImagesIndex() {
        return imagesIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.images_index
     *
     * @param imagesIndex the value for activity.images_index
     *
     * @mbg.generated
     */
    public void setImagesIndex(String imagesIndex) {
        this.imagesIndex = imagesIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.images
     *
     * @return the value of activity.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.images
     *
     * @param images the value for activity.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.type
     *
     * @return the value of activity.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.type
     *
     * @param type the value for activity.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.isplay
     *
     * @return the value of activity.isplay
     *
     * @mbg.generated
     */
    public String getIsplay() {
        return isplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.isplay
     *
     * @param isplay the value for activity.isplay
     *
     * @mbg.generated
     */
    public void setIsplay(String isplay) {
        this.isplay = isplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.sort
     *
     * @return the value of activity.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.sort
     *
     * @param sort the value for activity.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.territory
     *
     * @return the value of activity.territory
     *
     * @mbg.generated
     */
    public String getTerritory() {
        return territory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.territory
     *
     * @param territory the value for activity.territory
     *
     * @mbg.generated
     */
    public void setTerritory(String territory) {
        this.territory = territory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.territory2
     *
     * @return the value of activity.territory2
     *
     * @mbg.generated
     */
    public String getTerritory2() {
        return territory2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.territory2
     *
     * @param territory2 the value for activity.territory2
     *
     * @mbg.generated
     */
    public void setTerritory2(String territory2) {
        this.territory2 = territory2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.createid
     *
     * @return the value of activity.createid
     *
     * @mbg.generated
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.createid
     *
     * @param createid the value for activity.createid
     *
     * @mbg.generated
     */
    public void setCreateid(String createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.createtime
     *
     * @return the value of activity.createtime
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.createtime
     *
     * @param createtime the value for activity.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.updateid
     *
     * @return the value of activity.updateid
     *
     * @mbg.generated
     */
    public String getUpdateid() {
        return updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.updateid
     *
     * @param updateid the value for activity.updateid
     *
     * @mbg.generated
     */
    public void setUpdateid(String updateid) {
        this.updateid = updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.updatetime
     *
     * @return the value of activity.updatetime
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.updatetime
     *
     * @param updatetime the value for activity.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(LocalDateTime updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", place=").append(place);
        sb.append(", imagesIndex=").append(imagesIndex);
        sb.append(", images=").append(images);
        sb.append(", type=").append(type);
        sb.append(", isplay=").append(isplay);
        sb.append(", sort=").append(sort);
        sb.append(", territory=").append(territory);
        sb.append(", territory2=").append(territory2);
        sb.append(", createid=").append(createid);
        sb.append(", createtime=").append(createtime);
        sb.append(", updateid=").append(updateid);
        sb.append(", updatetime=").append(updatetime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Activity other = (Activity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPlace() == null ? other.getPlace() == null : this.getPlace().equals(other.getPlace()))
            && (this.getImagesIndex() == null ? other.getImagesIndex() == null : this.getImagesIndex().equals(other.getImagesIndex()))
            && (this.getImages() == null ? other.getImages() == null : this.getImages().equals(other.getImages()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getIsplay() == null ? other.getIsplay() == null : this.getIsplay().equals(other.getIsplay()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getTerritory() == null ? other.getTerritory() == null : this.getTerritory().equals(other.getTerritory()))
            && (this.getTerritory2() == null ? other.getTerritory2() == null : this.getTerritory2().equals(other.getTerritory2()))
            && (this.getCreateid() == null ? other.getCreateid() == null : this.getCreateid().equals(other.getCreateid()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdateid() == null ? other.getUpdateid() == null : this.getUpdateid().equals(other.getUpdateid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPlace() == null) ? 0 : getPlace().hashCode());
        result = prime * result + ((getImagesIndex() == null) ? 0 : getImagesIndex().hashCode());
        result = prime * result + ((getImages() == null) ? 0 : getImages().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getIsplay() == null) ? 0 : getIsplay().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getTerritory() == null) ? 0 : getTerritory().hashCode());
        result = prime * result + ((getTerritory2() == null) ? 0 : getTerritory2().hashCode());
        result = prime * result + ((getCreateid() == null) ? 0 : getCreateid().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdateid() == null) ? 0 : getUpdateid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table activity
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        place("place", "place", "VARCHAR", false),
        imagesIndex("images_index", "imagesIndex", "VARCHAR", false),
        images("images", "images", "VARCHAR", false),
        type("type", "type", "VARCHAR", true),
        isplay("isplay", "isplay", "VARCHAR", false),
        sort("sort", "sort", "INTEGER", false),
        territory("territory", "territory", "VARCHAR", false),
        territory2("territory2", "territory2", "VARCHAR", false),
        createid("createid", "createid", "VARCHAR", false),
        createtime("createtime", "createtime", "TIMESTAMP", false),
        updateid("updateid", "updateid", "VARCHAR", false),
        updatetime("updatetime", "updatetime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table activity
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table activity
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table activity
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table activity
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table activity
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table activity
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table activity
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}