package org.xhh.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class ProTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.PRO_NUM
     *
     * @mbg.generated
     */
    private Integer proNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.SKETCH
     *
     * @mbg.generated
     */
    private String sketch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.RATIO
     *
     * @mbg.generated
     */
    private String ratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.DEADLINE
     *
     * @mbg.generated
     */
    private String deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.CREATERID
     *
     * @mbg.generated
     */
    private String createrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.CREATER
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.ADD_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_task.UPDATE_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.ID
     *
     * @return the value of pro_task.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.ID
     *
     * @param id the value for pro_task.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.PRO_NUM
     *
     * @return the value of pro_task.PRO_NUM
     *
     * @mbg.generated
     */
    public Integer getProNum() {
        return proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.PRO_NUM
     *
     * @param proNum the value for pro_task.PRO_NUM
     *
     * @mbg.generated
     */
    public void setProNum(Integer proNum) {
        this.proNum = proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.SKETCH
     *
     * @return the value of pro_task.SKETCH
     *
     * @mbg.generated
     */
    public String getSketch() {
        return sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.SKETCH
     *
     * @param sketch the value for pro_task.SKETCH
     *
     * @mbg.generated
     */
    public void setSketch(String sketch) {
        this.sketch = sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.CONTENT
     *
     * @return the value of pro_task.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.CONTENT
     *
     * @param content the value for pro_task.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.RATIO
     *
     * @return the value of pro_task.RATIO
     *
     * @mbg.generated
     */
    public String getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.RATIO
     *
     * @param ratio the value for pro_task.RATIO
     *
     * @mbg.generated
     */
    public void setRatio(String ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.DEADLINE
     *
     * @return the value of pro_task.DEADLINE
     *
     * @mbg.generated
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.DEADLINE
     *
     * @param deadline the value for pro_task.DEADLINE
     *
     * @mbg.generated
     */
    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.STATUS
     *
     * @return the value of pro_task.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.STATUS
     *
     * @param status the value for pro_task.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.REMARK
     *
     * @return the value of pro_task.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.REMARK
     *
     * @param remark the value for pro_task.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.CREATERID
     *
     * @return the value of pro_task.CREATERID
     *
     * @mbg.generated
     */
    public String getCreaterid() {
        return createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.CREATERID
     *
     * @param createrid the value for pro_task.CREATERID
     *
     * @mbg.generated
     */
    public void setCreaterid(String createrid) {
        this.createrid = createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.CREATER
     *
     * @return the value of pro_task.CREATER
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.CREATER
     *
     * @param creater the value for pro_task.CREATER
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.ADD_TIME
     *
     * @return the value of pro_task.ADD_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.ADD_TIME
     *
     * @param addTime the value for pro_task.ADD_TIME
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_task.UPDATE_TIME
     *
     * @return the value of pro_task.UPDATE_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_task.UPDATE_TIME
     *
     * @param updateTime the value for pro_task.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_task
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", proNum=").append(proNum);
        sb.append(", sketch=").append(sketch);
        sb.append(", content=").append(content);
        sb.append(", ratio=").append(ratio);
        sb.append(", deadline=").append(deadline);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", createrid=").append(createrid);
        sb.append(", creater=").append(creater);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_task
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProTask other = (ProTask) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProNum() == null ? other.getProNum() == null : this.getProNum().equals(other.getProNum()))
            && (this.getSketch() == null ? other.getSketch() == null : this.getSketch().equals(other.getSketch()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getRatio() == null ? other.getRatio() == null : this.getRatio().equals(other.getRatio()))
            && (this.getDeadline() == null ? other.getDeadline() == null : this.getDeadline().equals(other.getDeadline()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreaterid() == null ? other.getCreaterid() == null : this.getCreaterid().equals(other.getCreaterid()))
            && (this.getCreater() == null ? other.getCreater() == null : this.getCreater().equals(other.getCreater()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_task
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProNum() == null) ? 0 : getProNum().hashCode());
        result = prime * result + ((getSketch() == null) ? 0 : getSketch().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getRatio() == null) ? 0 : getRatio().hashCode());
        result = prime * result + ((getDeadline() == null) ? 0 : getDeadline().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreaterid() == null) ? 0 : getCreaterid().hashCode());
        result = prime * result + ((getCreater() == null) ? 0 : getCreater().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table pro_task
     *
     * @mbg.generated
     */
    public enum Column {
        id("ID", "id", "INTEGER", false),
        proNum("PRO_NUM", "proNum", "INTEGER", false),
        sketch("SKETCH", "sketch", "VARCHAR", false),
        content("CONTENT", "content", "VARCHAR", false),
        ratio("RATIO", "ratio", "VARCHAR", false),
        deadline("DEADLINE", "deadline", "VARCHAR", false),
        status("STATUS", "status", "VARCHAR", true),
        remark("REMARK", "remark", "VARCHAR", false),
        createrid("CREATERID", "createrid", "VARCHAR", false),
        creater("CREATER", "creater", "VARCHAR", false),
        addTime("ADD_TIME", "addTime", "TIMESTAMP", false),
        updateTime("UPDATE_TIME", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table pro_task
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}