package org.xhh.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xhh.db.domain.Activityservemeal;
import org.xhh.db.domain.ActivityservemealExample;

public interface ActivityservemealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    long countByExample(ActivityservemealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    int deleteByExample(ActivityservemealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    int insert(Activityservemeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    int insertSelective(Activityservemeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    Activityservemeal selectOneByExample(ActivityservemealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    Activityservemeal selectOneByExampleSelective(@Param("example") ActivityservemealExample example, @Param("selective") Activityservemeal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    List<Activityservemeal> selectByExampleSelective(@Param("example") ActivityservemealExample example, @Param("selective") Activityservemeal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    List<Activityservemeal> selectByExample(ActivityservemealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    Activityservemeal selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Activityservemeal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    Activityservemeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Activityservemeal record, @Param("example") ActivityservemealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Activityservemeal record, @Param("example") ActivityservemealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Activityservemeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityservemeal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Activityservemeal record);
}