package org.xhh.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xhh.db.domain.Activitymeal;
import org.xhh.db.domain.ActivitymealExample;

public interface ActivitymealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    long countByExample(ActivitymealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    int deleteByExample(ActivitymealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    int insert(Activitymeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    int insertSelective(Activitymeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    Activitymeal selectOneByExample(ActivitymealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    Activitymeal selectOneByExampleSelective(@Param("example") ActivitymealExample example, @Param("selective") Activitymeal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    List<Activitymeal> selectByExampleSelective(@Param("example") ActivitymealExample example, @Param("selective") Activitymeal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    List<Activitymeal> selectByExample(ActivitymealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    Activitymeal selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Activitymeal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    Activitymeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Activitymeal record, @Param("example") ActivitymealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Activitymeal record, @Param("example") ActivitymealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Activitymeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitymeal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Activitymeal record);
}