package org.xhh.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xhh.db.domain.Activityserve;
import org.xhh.db.domain.ActivityserveExample;

public interface ActivityserveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    long countByExample(ActivityserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    int deleteByExample(ActivityserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    int insert(Activityserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    int insertSelective(Activityserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    Activityserve selectOneByExample(ActivityserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    Activityserve selectOneByExampleSelective(@Param("example") ActivityserveExample example, @Param("selective") Activityserve.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    List<Activityserve> selectByExampleSelective(@Param("example") ActivityserveExample example, @Param("selective") Activityserve.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    List<Activityserve> selectByExample(ActivityserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    Activityserve selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Activityserve.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    Activityserve selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Activityserve record, @Param("example") ActivityserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Activityserve record, @Param("example") ActivityserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Activityserve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activityserve
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Activityserve record);
}