package org.xhh.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xhh.db.domain.ProContent;
import org.xhh.db.domain.ProContentExample;

public interface ProContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    long countByExample(ProContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    int deleteByExample(ProContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    int insert(ProContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    int insertSelective(ProContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    ProContent selectOneByExample(ProContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    ProContent selectOneByExampleSelective(@Param("example") ProContentExample example, @Param("selective") ProContent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    List<ProContent> selectByExampleSelective(@Param("example") ProContentExample example, @Param("selective") ProContent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    List<ProContent> selectByExample(ProContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    ProContent selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ProContent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    ProContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProContent record, @Param("example") ProContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProContent record, @Param("example") ProContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProContent record);
}