package org.xhh.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xhh.db.domain.ProUser;
import org.xhh.db.domain.ProUserExample;

public interface ProUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    long countByExample(ProUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    int deleteByExample(ProUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    int insert(ProUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    int insertSelective(ProUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    ProUser selectOneByExample(ProUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    ProUser selectOneByExampleSelective(@Param("example") ProUserExample example, @Param("selective") ProUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    List<ProUser> selectByExampleSelective(@Param("example") ProUserExample example, @Param("selective") ProUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    List<ProUser> selectByExample(ProUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    ProUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ProUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    ProUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProUser record, @Param("example") ProUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProUser record, @Param("example") ProUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProUser record);
}