package org.xhh.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xhh.db.domain.ProUserpay;
import org.xhh.db.domain.ProUserpayExample;

public interface ProUserpayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    long countByExample(ProUserpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    int deleteByExample(ProUserpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    int insert(ProUserpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    int insertSelective(ProUserpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    ProUserpay selectOneByExample(ProUserpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    ProUserpay selectOneByExampleSelective(@Param("example") ProUserpayExample example, @Param("selective") ProUserpay.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    List<ProUserpay> selectByExampleSelective(@Param("example") ProUserpayExample example, @Param("selective") ProUserpay.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    List<ProUserpay> selectByExample(ProUserpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    ProUserpay selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ProUserpay.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    ProUserpay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProUserpay record, @Param("example") ProUserpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProUserpay record, @Param("example") ProUserpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProUserpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_userpay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProUserpay record);
}